### ISSUE TITLE
Required for all (client and server sides)

### ISSUE THREAD

**Issue by PC-Principal** [PC-Principal/extended_flashlight_range#1]
Need to make the mod required for everyone (host and players).

I would be glad to help in this matter :3

**Comment by ghost** [comment]
Товарищ, с тобой можно как то связаться?

**Comment by PC-Principal** [comment]
> Товарищ, с тобой можно как то связаться?

Discord: pc_principal9191

**Comment by PC-Principal** [comment]
> Товарищ, с тобой можно как то связаться?

Discord подойдет?

**Comment by ghost** [comment]
Да

**Comment by PC-Principal** [comment]
Not planned, until that not conflict with server connection from client-side.
