### ISSUE TITLE
Colorful flashlights compitability

### ISSUE THREAD

**Issue by Kingtonberry** [PC-Principal/extended_flashlight_range#3]
currently it seems to only work with the flashlight equipped, is it possible to keep it active while shoulder mounted? i have colorful flashlights, f for flashlight and flashlightfix not sure if one of those is effecting it. thanks!

**Comment by PC-Principal** [comment]
I'll check this feature, I suspect that it may add conflict with other mods.

**Comment by PC-Principal** [comment]
@Kingtonberry  What you are talking about is called helmet light, in the latest version **v1.0.9** I added light support, which will also now work with your mods.

**If everything works, I will be glad if you star this repository, after that you can close that issue.**

**Comment by PC-Principal** [comment]
Starting from **v1.1.0** you can see this more powerfull flashlight effect (including if you use it through a helmet with **F button**), working correct with Colorful flashlights - tested.

**Green-flashlight**
![222](https://github.com/PC-Principal/extended_flashlight_range/assets/22794848/6feddaf7-c6f4-471c-94eb-67e366b001d7)

**Pro-flashlight**
![111](https://github.com/PC-Principal/extended_flashlight_range/assets/22794848/f77bcd63-a783-46e4-840d-b3ca5f2a61db)
