### ISSUE TITLE
ReservedFlashlightSlot by FlipMods compitability

### ISSUE THREAD

**Issue by NeatWolf** [PC-Principal/extended_flashlight_range#4]
as per title, it's all good as you hold the flashlight, but when triggered via hotkey (ReservedFlashlightSlot by FlipMods) or it's not selected, the light is unchanged.

It's a bit of a shame because both mods are quite popular but don't coexist too well :/

**Comment by PC-Principal** [comment]
Thank you for your note, as soon as possible I will try to integrate it so that the mods can work together correctly.

**Comment by PC-Principal** [comment]
@NeatWolf  What you are talking about is called helmet light, in the latest version **v1.0.9** I added light support, which will also now work with your mods.

**If everything works, I will be glad if you star this repository, after that you can close that issue.**

**Comment by PC-Principal** [comment]
Starting from **v1.1.0** you can see this more powerfull flashlight effect (including if you use it through a helmet with **F button**).

**Green-flashlight**
![222](https://github.com/PC-Principal/extended_flashlight_range/assets/22794848/6feddaf7-c6f4-471c-94eb-67e366b001d7)

**Pro-flashlight**
![111](https://github.com/PC-Principal/extended_flashlight_range/assets/22794848/f77bcd63-a783-46e4-840d-b3ca5f2a61db)

**Comment by NeatWolf** [comment]
Getting back here to thank you for fixing it in such a timely manner! Much appreciated :)
(only now I realize it's sometimes a bit too bright with volumetrics and would be cool if radius/cone/intensity/volumetric amount  was configurable via LethalConfig - but that's another story :D )

**Comment by PC-Principal** [comment]
Hello again! Will be added with the next mod update)
